name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check files exist
        run: |
          test -f index.html
          test -d static
      - name: Ensure index.html not empty
        run: |
          test -s index.html
